name: Deployment

on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install packages
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Install Surge
        run: yarn global add surge

      - name: Deploy to surge
        run: surge ./out imagemods.surge.sh --token ${{secrets.SURGE_TOKEN}}
